final products = [
  {
    'id': '0',
    'title': 'Nike Air Force 1',
    'price': 150.58,
    'imageUrl': 'assets/images/shoes_1.png',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11, 12],
  },
  {
    'id': '1',
    'title': 'Nike Travis Air Jordan 1',
    'price': 499.99,
    'imageUrl': 'assets/images/shoes_2.png',
    'company': 'Nike',
    'sizes': [9, 10, 11, 12],
  },
  {
    'id': '2',
    'title': 'Nike Air Jordan 1',
    'price': 429.99,
    'imageUrl': 'assets/images/shoes_3.png',
    'company': 'Nike',
    'sizes': [9, 10, 11, 12],
  },
  {
    'id': '3',
    'title': 'New Balance 550',
    'price': 499.99,
    'imageUrl': 'assets/images/shoes_4.png',
    'company': 'New Balance',
    'sizes': [9, 10, 11, 12],
  },
  {
    'id': '4',
    'title': 'New Balance 530',
    'price': 399.99,
    'imageUrl': 'assets/images/shoes_5.png',
    'company': 'New Balance',
    'sizes': [9, 10, 11, 12],
  },
  {
    'id': '5',
    'title': 'Adidas Samba',
    'price': 299.99,
    'imageUrl': 'assets/images/shoes_6.png',
    'company': 'Addidas',
    'sizes': [9, 10, 11, 12],
  },
  {
    'id': '6',
    'title': 'Adidas Ozweego',
    'price': 499.99,
    'imageUrl': 'assets/images/shoes_7.png',
    'company': 'Adidas',
    'sizes': [9, 10, 11, 12],
  },
  {
    'id': '7',
    'title': 'Adidas Campus 00s',
    'price': 399.99,
    'imageUrl': 'assets/images/shoes_8.png',
    'company': 'Adidas',
    'sizes': [8, 9, 10, 11, 12],
  },
  {
    'id': '8',
    'title': 'Reebook club c 85',
    'price': 299.99,
    'imageUrl': 'assets/images/shoes_9.png',
    'company': 'Reebook',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '9',
    'title': 'Puma Suede',
    'price': 399.99,
    'imageUrl': 'assets/images/shoes_10.png',
    'company': 'Puma',
    'sizes': [8, 9, 10, 12],
  },
  {
    'id': '10',
    'title': 'Converse All Star',
    'price': 199.99,
    'imageUrl': 'assets/images/shoes_11.png',
    'company': 'Converse',
    'sizes': [9, 10, 11, 12],
  },
  {
    'id': '11',
    'title': 'Converse Run Star Hike',
    'price': 299.99,
    'imageUrl': 'assets/images/shoes_12.png',
    'company': 'Converse',
    'sizes': [8, 9, 10],
  },
  {
    'id': '12',
    'title': 'Vans Sneaker',
    'price': 399.99,
    'imageUrl': 'assets/images/shoes_13.png',
    'company': 'Vans',
    'sizes': [8, 9, 10, 11, 12],
  },
];

final cart = [
  {
    'id': '4',
    'title': 'New Balance 550',
    'price': 499.99,
    'imageUrl': 'assets/images/shoes_23.png',
    'company': 'New Balance',
    'sizes': [9, 10, 11, 12],
  },
];
